#!/bin/sh
# Läppärin oma näyttö pois päältä.
#xrandr --output eDP1 --off
#xrandr --output HDMI1 --auto
xrandr --newmode "1680x1050" 146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync
xrandr --addmode VGA-1 1680x1050
xrandr --output VGA-1 --mode 1680x1050 --right-of HDMI-1
