#!/bin/bash
#
# Start a composition manager.
# (picom in this case)

comphelp() {
    echo "Composition Manager:"
    echo "   (re)start: COMP"
    echo "   stop:      COMP -s"
    echo "   query:     COMP -q"
    echo "              returns 0 if composition manager is running, else 1"
    exit
}

checkcomp() {
    pgrep picom &>/dev/null
}

stopcomp() {
    checkcomp && killall picom
    notify-send "Compositing off"
}

togglecomp() {
  if pgrep picom &>/dev/null; then
    stopcomp
  else
    picom && notify-send "Compositing on"
  fi
  exit
}

case "$1" in
    "")   togglecomp ;;
    "-q") checkcomp ;;
    "-s") stopcomp; exit ;;
    *)    comphelp ;;
esac
