#!/bin/sh

# Some distros have in their default Zsh /etc/zshrc file to run compinit which
# enables completion. However, if user configs already do this it just introduces
# more startup delay so this comments that line out.

if [ $(id -u) -ne 0 ]; then
  echo "Error: Sudo required"
  exit 1
fi

if [ -f /etc/zshrc ]; then
  echo "Error: /etc/zshrc not found."
  exit 1
fi

# Commenting out lines containing "compinit" but are not already commented.
sed -e '/compinit/ s/^#*/#/' -i /etc/zshrc
