#!/bin/sh
echo "Stopping network service first, please enter password."
sudo systemctl is-active network.service && systemctl stop network.service
sleep 2
echo "Enabling NetworkManager.."
sudo systemctl --force enable NetworkManager.service
sleep 2
echo "Enabling nerwork service..".
sudo systemctl start network.service
echo "Done."