#!/bin/sh

# Dead simple: print months in english and finnish

echo "1  January   tammikuu
2  February  helmikuu
3  March     maaliskuu
4  April     huhtikuu
5  May       toukokuu
6  June      kesäkuu
7  July      heinäkuu
8  August    elokuu
9  September syyskuu
10 October   lokakuu
11 November  marraskuu
12 December  joulukuu"
