#!/bin/bash
# Quickly set system locale.

main_locale="fi_FI.UTF-8"
messages_locale="en_US.UTF-8"

locale_keys=(
  "CTYPE" "NUMERIC" "TIME" "COLLATE" "MONETARY" "PAPER" "NAME"\
  "ADDRESS" "TELEPHONE" "MEASUREMENT" "IDENTIFICATION"
)

for locale_key in "${locale_keys[@]}"
do
  export "LC_${locale_key}=$main_locale"
done

export LANG="$main_locale"
export LC_MESSAGES="$messages_locale"
