#!/bin/bash
# Usage: set_tab_title <title>

# Return if requirements are not found.
case "$TERM" in
  dumb|linux)
  return 1
esac

# Exit if one parameter isn't given.
if [ "$#" -ne 1 ]; then
  echo "Error: No title given."
  exit 1
fi

title="$1"

yakuake_set_title () {
  if [[ $UID == 0 ]] ; then   # Doesn't work if we are root.
    exit 1
  fi
    # Find out the right Yakuake session id.
    session_id="$(qdbus org.kde.yakuake /yakuake/sessions sessionIdList | tr , "\n" | sort -g | tail -1 | tr -d '\n')"
  qdbus org.kde.yakuake /yakuake/tabs setTabTitle $session_id "$title"
  exit
}

# Find out if we are running terminals that need special commands.
# Ongelma: jos on useampi terminaali avoinna, niin valitsee sen, joka ensimmäisenä mätsää.
if pgrep "yakuake" > /dev/null ; then
  yakuake_set_title
elif pgrep "terminator" > /dev/null|pgrep "terminology" > /dev/null; then
  # http://terminator-gtk3.readthedocs.io/en/latest/index.html
  printf '\033]0;%s\a' $title
else
  printf '\e]1;%s\a' $title
fi
exit
