#!/bin/sh

 MAPPER_NAME="ext-hdd"
 MOUNT_POINT="/mnt/ext-hdd"

 echo "Unmounting the filesystem from $MOUNT_POINT..."
 sudo umount "$MOUNT_POINT" || {
     echo "Failed to unmount the filesystem."
     return 1
 }

 echo "Closing LUKS partition..."
 sudo cryptsetup close "$MAPPER_NAME" || {
     echo "Failed to close LUKS partition."
     return 1
 }

 echo "LUKS partition unmounted and closed."
