#!/bin/zsh

# Update various software.

set -e

has() {
  command -v "$@" &> /dev/null
}

if has dnf; then
  sudo dnf upgrade
fi

# Flatpaks
if has flatpak; then
  echo -e "Updating flatpaks...\n"
  if flatpak info org.signal.Signal >/dev/null 2>&1; then
    flatpak update --assumeyes org.signal.Signal
  fi
fi

# Appimages

# appimage_update="$HOME/Applications/appimageupdatetool-x86_64.AppImage"
# neovide_appimage="$HOME/Applications/neovide.AppImage"
#
# if [ -x "$appimage_update" ] && [ -f "$neovide_appimage" ]; then
#     echo -e "Updating appimages...\n"
#     "$appimage_update" --remove-old "$neovide_appimage"
# fi

# Antidote is a Zsh plugin manager.  https://antidote.sh/
antidotefile="${XDG_DATA_HOME:-${HOME}/.local/share}/antidote/antidote.zsh"
if [ -f $antidotefile ]; then
  zstyle ':antidote:bundle' use-friendly-names 'yes'
  source $antidotefile
  # initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
  antidote load ${ZDOTDIR:-~}/zsh_plugins.txt
  antidote update
fi

# houseabsolute/ubi: The Universal Binary Installer
# https://github.com/houseabsolute/ubi
if ! has ubi; then
  echo "Install Ubi - Universal binary installer?"
  sudo curl --silent --location \
      https://raw.githubusercontent.com/houseabsolute/ubi/master/bootstrap/bootstrap-ubi.sh |
      sh
fi

if has ubi; then
  echo "Updating moor and ripgrep with ubi to /usr/local/bin .."
  if [[ ! -d  $HOME/.local/bin ]]; then
    mkdir $HOME/.local/bin
  fi
  sudo ubi --project walles/moor --in /usr/local/bin
  sudo ubi --project BurntSushi/ripgrep --in /usr/local/bin -e rg
  sudo ubi --project matheus-git/systemd-manager-tui --in /usr/local/bin
  ubi --project michel-kraemer/zsh-patina --in ~/.local/bin
fi

# bob: A version manager for neovim. https://github.com/MordechaiHadad/bob
if has bob; then
  bob update
fi

## Zsh framework

# ZINIT_HOME=${ZINIT_HOME:-$HOME/.local/share/zinit}
#
# if [[ -f $ZINIT_HOME/bin/zinit.zsh ]]; then
#   echo -e "Updating Zinit...\n"
#   source "$ZINIT_HOME/bin/zinit.zsh"
#   zinit self-update
#   zinit update --all
# fi
#
