#!/usr/bin/env bash

# Get definition of word from Urban dictionary.

function command_exists () {
    type "$1" &> /dev/null ;
}

function print_error() {
    printf "\e[31m Error \e[0m: %s \n" "$1"
}

# Check that required tools are installed
if ! command_exists lynx; then
    print_error "you need lynx to run this program. please visit: http://lynx.browser.org/"
    exit 1
fi

if ! command_exists xmllint; then
    print_error "you need libxml2 (xmllint) to run this program."
    exit 1
fi

# Check parameter
if [[ $# -eq 0 ]]; then
    print_error "usage: $0 \"<term to find>\""
    exit 1
fi

term="$1"
page_html=$(wget -O - -q "https://www.urbandictionary.com/define.php?term=$term")

definition=$(printf "%s" "$page_html" | xmllint --html --xpath \
    '(//div[contains(concat(" ", normalize-space(@class), " "), " definition ")])[1]' \
    - 2>/dev/null)

meaning=$(printf "%s" "$definition" | xmllint --html --xpath \
    '(//div[contains(concat(" ", normalize-space(@class), " "), " meaning ")])[1]' \
    - 2>/dev/null)

example=$(printf "%s" "$definition" | xmllint --html --xpath \
    '(//div[contains(concat(" ", normalize-space(@class), " "), " example ")])[1]' \
    - 2>/dev/null)

if [[ -z "$meaning" ]]; then
    print_error "no definition found for: $1"
    exit 1
fi

topDefinition=$(printf "\n%s%s%s\n" \
"<div>searching for: $1</div>" \
"<div>Meaning</div>${meaning}" \
"<div>Examples</div>${example}")

printf "\n"
echo ${topDefinition} | lynx -dump -nolist -stdin
